// const plugin = require('tailwindcss/plugin')
// TODO 等Ui出来，配置主题
// const colorVariable = require('@mertasan/tailwindcss-variables/colorVariable')

/**
 * @param {*} start
 * @param {*} end
 * @param {*} step
 * @param {*} hasUnit
 * @returns
 */
function makeRange(start, end, step, hasUnit) {
  let map = {};
  while (start <= end) {
    if (hasUnit) {
      map[start] = start + "rpx";
    } else {
      map[start] = start + "";
    }
    start += step;
  }
  return map;
}

module.exports = {
  // separator: '--',
  purge: {
    preserveHtmlElements: false,
    content: ["./public/*.html", "./src/**/*.vue", "./src/**/*.js"],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    colors: {
      primary: "#0076FF",
      info: "#B3D6FF",
      success: "#17BB89",
      danger: "#e72832",
      warning: "#FF8A21",
      main: "#333",
      secondary: "#5E5E5E",
      muted: "#999",
      note: "#c0c0c0",
      white: "#fff",
      black: "#000",
      disable: "#888",
      block: "#f5f5f5", // 色块背景
      placeholder: "#c6c6c6",
    },
    screens: {},
    spacing: makeRange(0, 100, 4, true),
    // borderColor: { DEFAULT: 'var(--colors-border)' },
    borderColor: {
      default: "#c6c6c6",
    },
    borderRadius: { ...makeRange(8, 32, 8, true), full: "50%" },
    borderWidth: { DEFAULT: "1rpx", 1: "1rpx" },
    fontSize: makeRange(8, 64, 4, true),
    fontWeight: makeRange(400, 800, 100),
    height: Object.assign(makeRange(10, 100, 2, true), {
      auto: "auto",
      full: "100%",
      screen: "100vh",
    }),
    width: Object.assign(makeRange(10, 200, 2, true), {
      1: "1rpx",
      auto: "auto",
      full: "100%",
      screen: "100vw",
    }),
    // 去掉margin负值
    margin: (theme) => ({ auto: "auto", ...theme("spacing") }),
    lineHeight: makeRange(16, 100, 4, true),
  },
  // https://v1.tailwindcss.com/docs/configuration#core-plugins
  corePlugins: [
    "display",
    "boxSizing",
    "flex",
    "alignContent",
    "alignItems",
    "alignSelf",
    "flexGrow",
    "flexDirection",
    "flexShrink",
    "flexWrap",
    "justifyContent",
    "justifyItems",
    "justifySelf",
    "backgroundColor",
    "borderColor",
    "borderRadius",
    "borderWidth",
    "borderStyle",
    "margin",
    "padding",
    "fontSize",
    "fontWeight",
    "width",
    "height",
    "lineHeight",
    "overflow",
    "position",
    "textAlign",
    "textColor",
    "wordBreak",
    "zIndex",
    "float",
  ],
  // 去掉响应式和伪类，小程序不支持
  variants: {
    accessibility: [],
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    animation: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundClip: [],
    backgroundColor: [],
    backgroundImage: [],
    backgroundOpacity: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: [],
    borderOpacity: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: [],
    boxSizing: [],
    clear: [],
    container: [],
    cursor: [],
    display: [],
    divideColor: [],
    divideOpacity: [],
    divideStyle: [],
    divideWidth: [],
    fill: [],
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: [],
    fontFamily: [],
    fontSize: [],
    fontSmoothing: [],
    fontStyle: [],
    fontVariantNumeric: [],
    fontWeight: [],
    gap: [],
    gradientColorStops: [],
    gridAutoColumns: [],
    gridAutoFlow: [],
    gridAutoRows: [],
    gridColumn: [],
    gridColumnEnd: [],
    gridColumnStart: [],
    gridRow: [],
    gridRowEnd: [],
    gridRowStart: [],
    gridTemplateColumns: [],
    gridTemplateRows: [],
    height: [],
    inset: [],
    justifyContent: [],
    justifyItems: [],
    justifySelf: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: [],
    order: [],
    outline: [],
    overflow: [],
    overscrollBehavior: [],
    padding: [],
    placeContent: [],
    placeItems: [],
    placeSelf: [],
    placeholderColor: [],
    placeholderOpacity: [],
    pointerEvents: [],
    position: [],
    resize: [],
    ringColor: [],
    ringOffsetColor: [],
    ringOffsetWidth: [],
    ringOpacity: [],
    ringWidth: [],
    rotate: [],
    scale: [],
    skew: [],
    space: [],
    stroke: [],
    strokeWidth: [],
    tableLayout: [],
    textAlign: [],
    textColor: [],
    textDecoration: [],
    textOpacity: [],
    textOverflow: [],
    textTransform: [],
    transform: [],
    transformOrigin: [],
    transitionDelay: [],
    transitionDuration: [],
    transitionProperty: [],
    transitionTimingFunction: [],
    translate: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: [],
  },
};
